dist: xenial
language: python
python: 3.7
stages:
  - test
  - build
  - deploy
jobs:
  include:
    - stage: test
      name: flake8
      install:
        - pip install -r requirements.txt
        - travis_retry pip install -U flake8
      script:
        - flake8 --version
        - flake8 cloudflare_ddns;
        - flake8 run.py;
    - stage: test
      name: pylint
      install:
        - pip install -r requirements.txt
        - travis_retry pip install -U pylint
      script:
        - pylint --version
        - pylint cloudflare_ddns;
        - pylint run.py;

before_install:
  - deactivate
  - /opt/python/3.7.1/bin/python -m venv ~/venv
  - source ~/venv/bin/activate
