dist: xenial
language: python
python: 3.7
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: flake8
      install:
        - travis_retry pip install -r requirements.txt
        - travis_retry pip install -U flake8
      script:
        - flake8 cloudflare_ddns
        - flake8 run.py
    - stage: test
      name: pylint
      before_install:
        - deactivate
        - /opt/python/3.7.1/bin/python -m venv ~/venv
        - source ~/venv/bin/activate
      install:
        - travis_retry pip install -r requirements.txt
        - travis_retry pip install -U pylint
      script:
        - pylint cloudflare_ddns
        - pylint run.py
    - stage: deploy
      name: mkdocs
      dist: trusty
      if: branch = master
      install:
        - travis_retry pip install -U mkdocs mkdocs-material
      script:
        - mkdocs build --clean --strict
      deploy:
        provider: pages
        skip-cleanup: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        local-dir: site
        on:
          branch: master
