site_name: Cloudflare DDNS
theme:
  name: material
  palette:
    primary: amber
    accent: amber

repo_name: joshuaavalon/cloudflare-ddns
repo_url: https://github.com/joshuaavalon/cloudflare-ddns

extra:
  social:
    - type: github-alt
      link: https://github.com/joshuaavalon/cloudflare-ddns
